// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuR8w5fZmUpnkOtig_tT9LNxU9V0rDdU',
    appId: '1:717752141776:web:15cc534cf78cd9cfbe5bd5',
    messagingSenderId: '717752141776',
    projectId: 'geonotify-2beb5',
    authDomain: 'geonotify-2beb5.firebaseapp.com',
    storageBucket: 'geonotify-2beb5.firebasestorage.app',
    measurementId: 'G-7YMHWR4EPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJNn_Oi2OTrHyfI3tNWcTmpcUkvXhWZno',
    appId: '1:717752141776:android:114f92f649d3711ebe5bd5',
    messagingSenderId: '717752141776',
    projectId: 'geonotify-2beb5',
    storageBucket: 'geonotify-2beb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLi8mAqknhwGsy9fd-hP6vNxygi-2FhiY',
    appId: '1:717752141776:ios:aff68262b499059abe5bd5',
    messagingSenderId: '717752141776',
    projectId: 'geonotify-2beb5',
    storageBucket: 'geonotify-2beb5.firebasestorage.app',
    iosBundleId: 'com.example.remindx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLi8mAqknhwGsy9fd-hP6vNxygi-2FhiY',
    appId: '1:717752141776:ios:aff68262b499059abe5bd5',
    messagingSenderId: '717752141776',
    projectId: 'geonotify-2beb5',
    storageBucket: 'geonotify-2beb5.firebasestorage.app',
    iosBundleId: 'com.example.remindx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjuR8w5fZmUpnkOtig_tT9LNxU9V0rDdU',
    appId: '1:717752141776:web:d46d85744580807cbe5bd5',
    messagingSenderId: '717752141776',
    projectId: 'geonotify-2beb5',
    authDomain: 'geonotify-2beb5.firebaseapp.com',
    storageBucket: 'geonotify-2beb5.firebasestorage.app',
    measurementId: 'G-BCECC2JPKR',
  );
}
